logging:
  file:
    name: admin-activities-manager.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: admin-activites-manager
  datasource:
    password: password1
    url: jdbc:mysql://flightapp.c8oyd2gnbiym.us-east-1.rds.amazonaws.com/flightapp
    username: admin
   #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active:
    - staging  
jwt:
  secret: access**access

